"""Session IDs must be derived from Eastern time, not the process/container
timezone.

Match rows always store `datetime` in US/Eastern (see the write path at
`app.py` around `EASTERN = pytz.timezone("US/Eastern")`), but session IDs are
generated by feeding `datetime.fromtimestamp(...)` results into
`_generate_session_id`. Before this fix, `fromtimestamp` used the naive
(process-local) timezone: on the Fly container -- which sets no TZ and so
runs UTC -- a late-evening ET game would mint a session ID stamped with the
*next* UTC day. Dev machines are usually already ET, so this never
reproduced locally.

These tests seed a single old game (>4h before the new game, to force
`_get_or_create_session_id` down the "start new session" branch that calls
`_generate_session_id`) and then log a game timestamped late evening ET /
past midnight UTC, asserting the resulting session ID carries the ET date.
"""

import os
import time
from datetime import datetime
from pathlib import Path
from types import ModuleType

import pandas as pd
import pytz

EASTERN = pytz.timezone("US/Eastern")


def _write_single_row_seed(
    csv_path: Path, dt_str: str, timestamp: float, session_id: str
) -> None:
    row = {
        "datetime": dt_str,
        "shayne_character": "Fox",
        "matt_character": "Falco",
        "winner": "Matt",
        "stocks_remaining": 2,
        "stage": "Battlefield",
        "timestamp": timestamp,
        "session_id": session_id,
        "match_id": "seedmatch0001",
    }
    pd.DataFrame([row]).to_csv(csv_path, index=False)


def _seed_old_game(data_dir: Path) -> None:
    """A single game far enough in the past (>4h) that the next logged game
    starts a brand new session, forcing `_generate_session_id` to run."""
    old_dt = EASTERN.localize(datetime(2025, 12, 11, 10, 0, 0))
    _write_single_row_seed(
        data_dir / "game_results.csv",
        old_dt.strftime("%Y-%m-%d %H:%M:%S"),
        old_dt.timestamp(),
        "2025-12-11-10",
    )


class TestSessionIdTimezone:
    def test_utc_midnight_crossing_uses_eastern_date(
        self, appmod: ModuleType, data_dir: Path
    ) -> None:
        _seed_old_game(data_dir)

        # 2025-12-11 23:30:00 US/Eastern == 2025-12-12 04:30 UTC: still
        # evening in ET, but already past midnight in UTC.
        new_game_dt = EASTERN.localize(datetime(2025, 12, 11, 23, 30, 0))
        epoch = new_game_dt.timestamp()

        session_id = appmod.data_manager._get_or_create_session_id(epoch)

        assert session_id.startswith("2025-12-11")

    def test_session_id_independent_of_process_timezone(
        self, appmod: ModuleType, data_dir: Path
    ) -> None:
        """Same assertion, but with the process TZ forced to UTC first --
        i.e. what CI already runs under, made explicit so this also proves
        something on an ET dev machine."""
        _seed_old_game(data_dir)

        new_game_dt = EASTERN.localize(datetime(2025, 12, 11, 23, 30, 0))
        epoch = new_game_dt.timestamp()

        prior_tz = os.environ.get("TZ")
        os.environ["TZ"] = "UTC"
        time.tzset()
        try:
            session_id = appmod.data_manager._get_or_create_session_id(epoch)
        finally:
            if prior_tz is None:
                os.environ.pop("TZ", None)
            else:
                os.environ["TZ"] = prior_tz
            time.tzset()

        assert session_id.startswith("2025-12-11")
